name: Run Backend Tests (CI)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.5
        options: --privileged 
    
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for Docker Compose
        run: |
          echo "DATABASE_URL=mongodb://mongo:27017/test-btc-lending" > .env
          echo "DEV_PORT=3000" >> .env
          echo "PROD_PORT=3001" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Run test container via Docker Compose
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          docker compose -f docker-compose.yml build test
          docker compose -f docker-compose.yml run --rm test 2>&1 | tee test-results.log
      
      - name: Upload test results as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: test-results.log
          retention-days: 30
      
      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "test-results.log"
          comment_mode: always
          compare_to_earlier_commit: true

      - name: Clean up containers
        if: always()
        run: docker compose down -v

      
